# coding: utf-8

"""
    \"Agent Toolkit: LLM-Friendly Tools and Search APIs\"

    API for LLM-friendly web search and content retrieval

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from at_client.api.default_api import DefaultApi  # noqa: E501


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        self.api.api_client.close()

    def test_auth_google_options_api_v1_auth_google_options(self) -> None:
        """Test case for auth_google_options_api_v1_auth_google_options

        Auth Google Options  # noqa: E501
        """
        pass

    def test_auth_logout_options_api_v1_auth_logout_options(self) -> None:
        """Test case for auth_logout_options_api_v1_auth_logout_options

        Auth Logout Options  # noqa: E501
        """
        pass

    def test_auth_me_options_api_v1_auth_me_options(self) -> None:
        """Test case for auth_me_options_api_v1_auth_me_options

        Auth Me Options  # noqa: E501
        """
        pass

    def test_create_api_key_endpoint_api_v1_api_keys_post(self) -> None:
        """Test case for create_api_key_endpoint_api_v1_api_keys_post

        Create Api Key Endpoint  # noqa: E501
        """
        pass

    def test_extract_content_api_v1_extract_post(self) -> None:
        """Test case for extract_content_api_v1_extract_post

        Extract Content  # noqa: E501
        """
        pass

    def test_extract_content_get_api_v1_extract_get(self) -> None:
        """Test case for extract_content_get_api_v1_extract_get

        Extract Content Get  # noqa: E501
        """
        pass

    def test_get_current_user_info_api_v1_auth_me_get(self) -> None:
        """Test case for get_current_user_info_api_v1_auth_me_get

        Get Current User Info  # noqa: E501
        """
        pass

    def test_get_providers_api_v1_providers_get(self) -> None:
        """Test case for get_providers_api_v1_providers_get

        Get Providers  # noqa: E501
        """
        pass

    def test_google_auth_api_v1_auth_google_post(self) -> None:
        """Test case for google_auth_api_v1_auth_google_post

        Google Auth  # noqa: E501
        """
        pass

    def test_list_api_keys_api_v1_api_keys_get(self) -> None:
        """Test case for list_api_keys_api_v1_api_keys_get

        List Api Keys  # noqa: E501
        """
        pass

    def test_logout_api_v1_auth_logout_post(self) -> None:
        """Test case for logout_api_v1_auth_logout_post

        Logout  # noqa: E501
        """
        pass

    def test_providers_options_api_v1_providers_options(self) -> None:
        """Test case for providers_options_api_v1_providers_options

        Providers Options  # noqa: E501
        """
        pass

    def test_root_get(self) -> None:
        """Test case for root_get

        Root  # noqa: E501
        """
        pass

    def test_search_api_v1_search_get(self) -> None:
        """Test case for search_api_v1_search_get

        Search  # noqa: E501
        """
        pass

    def test_update_api_key_status_endpoint_api_v1_api_keys_key_id_status_put(self) -> None:
        """Test case for update_api_key_status_endpoint_api_v1_api_keys_key_id_status_put

        Update Api Key Status Endpoint  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
