# coding: utf-8

"""
    \"Agent Toolkit: LLM-Friendly Tools and Search APIs\"

    API for LLM-friendly web search and content retrieval

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from at_client.models.app_schemas_search_error_response import AppSchemasSearchErrorResponse  # noqa: E501

class TestAppSchemasSearchErrorResponse(unittest.TestCase):
    """AppSchemasSearchErrorResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppSchemasSearchErrorResponse:
        """Test AppSchemasSearchErrorResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppSchemasSearchErrorResponse`
        """
        model = AppSchemasSearchErrorResponse()  # noqa: E501
        if include_optional:
            return AppSchemasSearchErrorResponse(
                detail = ''
            )
        else:
            return AppSchemasSearchErrorResponse(
                detail = '',
        )
        """

    def testAppSchemasSearchErrorResponse(self):
        """Test AppSchemasSearchErrorResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
