# coding: utf-8

"""
    \"Agent Toolkit: LLM-Friendly Tools and Search APIs\"

    API for LLM-friendly web search and content retrieval

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from at_client.api.credits_api import CreditsApi  # noqa: E501


class TestCreditsApi(unittest.TestCase):
    """CreditsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CreditsApi()

    def tearDown(self) -> None:
        self.api.api_client.close()

    def test_get_credits_api_v1_credits_get(self) -> None:
        """Test case for get_credits_api_v1_credits_get

        Get Credits  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
