# coding: utf-8

"""
    \"Agent Toolkit: LLM-Friendly Tools and Search APIs\"

    API for LLM-friendly web search and content retrieval

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from at_client.models.api_key_response import ApiKeyResponse  # noqa: E501

class TestApiKeyResponse(unittest.TestCase):
    """ApiKeyResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiKeyResponse:
        """Test ApiKeyResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiKeyResponse`
        """
        model = ApiKeyResponse()  # noqa: E501
        if include_optional:
            return ApiKeyResponse(
                key_id = '',
                api_key = '',
                name = '',
                tier = 'development',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                rate_limit = 56
            )
        else:
            return ApiKeyResponse(
                key_id = '',
                api_key = '',
                name = '',
                tier = 'development',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                rate_limit = 56,
        )
        """

    def testApiKeyResponse(self):
        """Test ApiKeyResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
