# coding: utf-8

"""
    \"Agent Toolkit: LLM-Friendly Tools and Search APIs\"

    API for LLM-friendly web search and content retrieval

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from at_client.models.rate_limit_tier import RateLimitTier  # noqa: E501

class TestRateLimitTier(unittest.TestCase):
    """RateLimitTier unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRateLimitTier(self):
        """Test RateLimitTier"""
        # inst = RateLimitTier()

if __name__ == '__main__':
    unittest.main()
