# coding: utf-8

"""
    \"Agent Toolkit: LLM-Friendly Tools and Search APIs\"

    API for LLM-friendly web search and content retrieval

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from at_client.models.extract_response import ExtractResponse  # noqa: E501

class TestExtractResponse(unittest.TestCase):
    """ExtractResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExtractResponse:
        """Test ExtractResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExtractResponse`
        """
        model = ExtractResponse()  # noqa: E501
        if include_optional:
            return ExtractResponse(
                results = [
                    at_client.models.extract_result.ExtractResult(
                        url = '', 
                        raw_content = '', 
                        images = [
                            ''
                            ], 
                        links = [
                            ''
                            ], 
                        cache_hit = True, )
                    ],
                failed_results = [
                    at_client.models.failed_result.FailedResult(
                        url = '', 
                        error = '', )
                    ],
                response_time = 1.337
            )
        else:
            return ExtractResponse(
                response_time = 1.337,
        )
        """

    def testExtractResponse(self):
        """Test ExtractResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
