# coding: utf-8

"""
    \"Agent Toolkit: LLM-Friendly Tools and Search APIs\"

    API for LLM-friendly web search and content retrieval

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from at_client.api.test_api import TestApi  # noqa: E501


class TestTestApi(unittest.TestCase):
    """TestApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TestApi()

    def tearDown(self) -> None:
        self.api.api_client.close()

    def test_test_rate_limit_api_v1_test_rate_limit_get(self) -> None:
        """Test case for test_rate_limit_api_v1_test_rate_limit_get

        Test Rate Limit  # noqa: E501
        """
        pass

    def test_test_rate_limit_api_v1_test_rate_limit_get_0(self) -> None:
        """Test case for test_rate_limit_api_v1_test_rate_limit_get_0

        Test Rate Limit  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
