# coding: utf-8

"""
    \"Agent Toolkit: LLM-Friendly Tools and Search APIs\"

    API for LLM-friendly web search and content retrieval

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class ApiKeyStatus(str, Enum):
    """
    Status of an API key
    """

    """
    allowed enum values
    """
    ACTIVE = 'active'
    DISABLED = 'disabled'
    REVOKED = 'revoked'

    @classmethod
    def from_json(cls, json_str: str) -> ApiKeyStatus:
        """Create an instance of ApiKeyStatus from a JSON string"""
        return ApiKeyStatus(json.loads(json_str))


