# coding: utf-8

"""
    \"Agent Toolkit: LLM-Friendly Tools and Search APIs\"

    API for LLM-friendly web search and content retrieval

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Dict, List, Optional
from pydantic import BaseModel, Field, StrictStr, conlist

class AppModelsCoreErrorResponse(BaseModel):
    """
    Standard error response model  # noqa: E501
    """
    detail: StrictStr = Field(default=..., description="Error message")
    code: Optional[StrictStr] = None
    errors: Optional[Dict[str, conlist(StrictStr)]] = None
    __properties = ["detail", "code", "errors"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> AppModelsCoreErrorResponse:
        """Create an instance of AppModelsCoreErrorResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if code (nullable) is None
        # and __fields_set__ contains the field
        if self.code is None and "code" in self.__fields_set__:
            _dict['code'] = None

        # set to None if errors (nullable) is None
        # and __fields_set__ contains the field
        if self.errors is None and "errors" in self.__fields_set__:
            _dict['errors'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> AppModelsCoreErrorResponse:
        """Create an instance of AppModelsCoreErrorResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return AppModelsCoreErrorResponse.parse_obj(obj)

        _obj = AppModelsCoreErrorResponse.parse_obj({
            "detail": obj.get("detail"),
            "code": obj.get("code"),
            "errors": obj.get("errors")
        })
        return _obj


