# coding: utf-8

"""
    \"Agent Toolkit: LLM-Friendly Tools and Search APIs\"

    API for LLM-friendly web search and content retrieval

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional, Union
from pydantic import BaseModel, Field, StrictFloat, StrictInt, conlist
from at_client.models.extract_result import ExtractResult
from at_client.models.failed_result import FailedResult

class ExtractResponse(BaseModel):
    """
    Schema for extract response.  # noqa: E501
    """
    results: Optional[conlist(ExtractResult)] = Field(default=None, description="List of successful extractions.")
    failed_results: Optional[conlist(FailedResult)] = Field(default=None, description="List of failed extractions.")
    response_time: Union[StrictFloat, StrictInt] = Field(default=..., description="Time in seconds it took to complete the request.")
    __properties = ["results", "failed_results", "response_time"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ExtractResponse:
        """Create an instance of ExtractResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in results (list)
        _items = []
        if self.results:
            for _item in self.results:
                if _item:
                    _items.append(_item.to_dict())
            _dict['results'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in failed_results (list)
        _items = []
        if self.failed_results:
            for _item in self.failed_results:
                if _item:
                    _items.append(_item.to_dict())
            _dict['failed_results'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ExtractResponse:
        """Create an instance of ExtractResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ExtractResponse.parse_obj(obj)

        _obj = ExtractResponse.parse_obj({
            "results": [ExtractResult.from_dict(_item) for _item in obj.get("results")] if obj.get("results") is not None else None,
            "failed_results": [FailedResult.from_dict(_item) for _item in obj.get("failed_results")] if obj.get("failed_results") is not None else None,
            "response_time": obj.get("response_time")
        })
        return _obj


