# coding: utf-8

"""
    \"Agent Toolkit: LLM-Friendly Tools and Search APIs\"

    API for LLM-friendly web search and content retrieval

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class RateLimitTier(str, Enum):
    """
    API Usage Tiers
    """

    """
    allowed enum values
    """
    DEVELOPMENT = 'development'
    PRODUCTION = 'production'

    @classmethod
    def from_json(cls, json_str: str) -> RateLimitTier:
        """Create an instance of RateLimitTier from a JSON string"""
        return RateLimitTier(json.loads(json_str))


